# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [ ]:
import numpy as np
import itertools

def inpute():
    while True:
        inp = input("Matrex size = ")
        try:
            inp = int(inp)  
            if inp > 0: 
                return inp 
            else:
                print("Please enter a positive number.")  
        except ValueError:
            print("Invalid input. Please enter a whole number.")  
dim = inpute()
def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    return np.random.randint(10, size=(dim, dim))

matrix = random_matrix(dim)

def generate_permutations(n):
    """
    Generate all permutations of numbers from 0 to n-1.
    """
    return list(itertools.permutations(range(n)))
def count_inversions(perm):
    inversions = 0
    n = len(perm)
    for i in range(n):
        for j in range(i + 1, n):
            if perm[i] > perm[j]:
                inversions += 1
    return inversions
def determinant(matrix):
    n = len(matrix)
    det = 0
    for perm in generate_permutations(n):
        sign = (-1) ** count_inversions(perm)
        product = 1
        for i in range(n):
            product *= matrix[i][perm[i]]
        det += sign * product

    return det
def prints():
    if dim > 0:
        print("\nMatrix:")
        print(matrix)
        print(random_matrix.__doc__)
        print("\nPermutations of indices:")
        print(generate_permutations(dim), generate_permutations.__doc__)
        print("\nDeterminant of matrix:")
        print(determinant(matrix))
prints()



Matrix:
[[5 9 1 1 2 8]
 [0 7 4 0 0 3]
 [0 4 0 4 2 4]
 [7 6 6 0 3 6]
 [4 9 8 9 8 9]
 [0 7 7 3 5 1]]

    The function generates dim x dim array of integers
    between 0 and 10.
    

Permutations of indices:
[(0, 1, 2, 3, 4, 5), (0, 1, 2, 3, 5, 4), (0, 1, 2, 4, 3, 5), (0, 1, 2, 4, 5, 3), (0, 1, 2, 5, 3, 4), (0, 1, 2, 5, 4, 3), (0, 1, 3, 2, 4, 5), (0, 1, 3, 2, 5, 4), (0, 1, 3, 4, 2, 5), (0, 1, 3, 4, 5, 2), (0, 1, 3, 5, 2, 4), (0, 1, 3, 5, 4, 2), (0, 1, 4, 2, 3, 5), (0, 1, 4, 2, 5, 3), (0, 1, 4, 3, 2, 5), (0, 1, 4, 3, 5, 2), (0, 1, 4, 5, 2, 3), (0, 1, 4, 5, 3, 2), (0, 1, 5, 2, 3, 4), (0, 1, 5, 2, 4, 3), (0, 1, 5, 3, 2, 4), (0, 1, 5, 3, 4, 2), (0, 1, 5, 4, 2, 3), (0, 1, 5, 4, 3, 2), (0, 2, 1, 3, 4, 5), (0, 2, 1, 3, 5, 4), (0, 2, 1, 4, 3, 5), (0, 2, 1, 4, 5, 3), (0, 2, 1, 5, 3, 4), (0, 2, 1, 5, 4, 3), (0, 2, 3, 1, 4, 5), (0, 2, 3, 1, 5, 4), (0, 2, 3, 4, 1, 5), (0, 2, 3, 4, 5, 1), (0, 2, 3, 5, 1, 4), (0, 2, 3, 5, 4, 1), (0, 2, 4, 1, 3, 5), (0, 2, 4, 1, 5, 3), (0, 2, 4, 3, 1, 5), (0, 2, 4, 